export const SEARCH_REPOS = 'SEARCH_REPOS';
export const SEARCH_REPOS_FAILED = 'SEARCH_REPOS_FAILED';
export const SEARCH_REPOS_SUCCESSFUL = 'SEARCH_REPOS_SUCCESSFUL';

export const UPDATE_SORT = 'UPDATE_SORT';
